version: "3.9"
services:
  mentoria-gupy-db:
    image: postgres:14.5-alpine3.16
    container_name: mentoria-gupy-db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
  mentoria-gupy-backend:
    image: izaubarbosa/mentoria-gupy-backend
    container_name: mentoria-gupy-backend
    networks:
      - mentoria-gupy-network
    ports:
      - 8000:8000

networks:
  mentoria-gupy-network:
    driver: bridge